# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

main_cpp <- function(args) {
    .Call(`_malariatrialpk_main_cpp`, args)
}

get_loglike_cpp <- function(args) {
    .Call(`_malariatrialpk_get_loglike_cpp`, args)
}

